package com.sudoku;

import java.util.ArrayList;
import java.util.List;

public class SudokuBootstrap {

    public static void main(String[] args) {
        List<Sudoku> total = new ArrayList<>(9 * 9);

        total.add(new Sudoku(1, 1, 1, 1));
        total.add(new Sudoku(1, 2, 1, 0));
        total.add(new Sudoku(1, 3, 1, 4));
        total.add(new Sudoku(1, 4, 2, 0));
        total.add(new Sudoku(1, 5, 2, 0));
        total.add(new Sudoku(1, 6, 2, 0));
        total.add(new Sudoku(1, 7, 3, 0));
        total.add(new Sudoku(1, 8, 3, 0));
        total.add(new Sudoku(1, 9, 3, 0));
        total.add(new Sudoku(2, 1, 1, 0));
        total.add(new Sudoku(2, 2, 1, 0));
        total.add(new Sudoku(2, 3, 1, 0));
        total.add(new Sudoku(2, 4, 2, 0));
        total.add(new Sudoku(2, 5, 2, 0));
        total.add(new Sudoku(2, 6, 2, 5));
        total.add(new Sudoku(2, 7, 3, 0));
        total.add(new Sudoku(2, 8, 3, 0));
        total.add(new Sudoku(2, 9, 3, 0));
        total.add(new Sudoku(3, 1, 1, 0));
        total.add(new Sudoku(3, 2, 1, 6));
        total.add(new Sudoku(3, 3, 1, 0));
        total.add(new Sudoku(3, 4, 2, 0));
        total.add(new Sudoku(3, 5, 2, 8));
        total.add(new Sudoku(3, 6, 2, 0));
        total.add(new Sudoku(3, 7, 3, 0));
        total.add(new Sudoku(3, 8, 3, 7));
        total.add(new Sudoku(3, 9, 3, 3));
        total.add(new Sudoku(4, 1, 4, 0));
        total.add(new Sudoku(4, 2, 4, 0));
        total.add(new Sudoku(4, 3, 4, 0));
        total.add(new Sudoku(4, 4, 5, 8));
        total.add(new Sudoku(4, 5, 5, 0));
        total.add(new Sudoku(4, 6, 5, 1));
        total.add(new Sudoku(4, 7, 6, 9));
        total.add(new Sudoku(4, 8, 6, 0));
        total.add(new Sudoku(4, 9, 6, 0));
        total.add(new Sudoku(5, 1, 4, 6));
        total.add(new Sudoku(5, 2, 4, 5));
        total.add(new Sudoku(5, 3, 4, 0));
        total.add(new Sudoku(5, 4, 5, 0));
        total.add(new Sudoku(5, 5, 5, 0));
        total.add(new Sudoku(5, 6, 5, 0));
        total.add(new Sudoku(5, 7, 6, 0));
        total.add(new Sudoku(5, 8, 6, 0));
        total.add(new Sudoku(5, 9, 6, 0));
        total.add(new Sudoku(6, 1, 4, 0));
        total.add(new Sudoku(6, 2, 4, 0));
        total.add(new Sudoku(6, 3, 4, 0));
        total.add(new Sudoku(6, 4, 5, 3));
        total.add(new Sudoku(6, 5, 5, 0));
        total.add(new Sudoku(6, 6, 5, 0));
        total.add(new Sudoku(6, 7, 6, 0));
        total.add(new Sudoku(6, 8, 6, 0));
        total.add(new Sudoku(6, 9, 6, 8));
        total.add(new Sudoku(7, 1, 7, 0));
        total.add(new Sudoku(7, 2, 7, 2));
        total.add(new Sudoku(7, 3, 7, 0));
        total.add(new Sudoku(7, 4, 8, 0));
        total.add(new Sudoku(7, 5, 8, 3));
        total.add(new Sudoku(7, 6, 8, 0));
        total.add(new Sudoku(7, 7, 9, 0));
        total.add(new Sudoku(7, 8, 9, 0));
        total.add(new Sudoku(7, 9, 9, 7));
        total.add(new Sudoku(8, 1, 7, 0));
        total.add(new Sudoku(8, 2, 7, 0));
        total.add(new Sudoku(8, 3, 7, 0));
        total.add(new Sudoku(8, 4, 8, 0));
        total.add(new Sudoku(8, 5, 8, 0));
        total.add(new Sudoku(8, 6, 8, 7));
        total.add(new Sudoku(8, 7, 9, 1));
        total.add(new Sudoku(8, 8, 9, 3));
        total.add(new Sudoku(8, 9, 9, 0));
        total.add(new Sudoku(9, 1, 7, 4));
        total.add(new Sudoku(9, 2, 7, 7));
        total.add(new Sudoku(9, 3, 7, 0));
        total.add(new Sudoku(9, 4, 8, 0));
        total.add(new Sudoku(9, 5, 8, 0));
        total.add(new Sudoku(9, 6, 8, 0));
        total.add(new Sudoku(9, 7, 9, 8));
        total.add(new Sudoku(9, 8, 9, 9));
        total.add(new Sudoku(9, 9, 9, 0));

        /*
        total.add(new Sudoku(1, 1, 1, 0));
        total.add(new Sudoku(1, 2, 1, 0));
        total.add(new Sudoku(1, 3, 1, 0));
        total.add(new Sudoku(1, 4, 2, 0));
        total.add(new Sudoku(1, 5, 2, 0));
        total.add(new Sudoku(1, 6, 2, 0));
        total.add(new Sudoku(1, 7, 3, 0));
        total.add(new Sudoku(1, 8, 3, 0));
        total.add(new Sudoku(1, 9, 3, 0));
        total.add(new Sudoku(2, 1, 1, 0));
        total.add(new Sudoku(2, 2, 1, 0));
        total.add(new Sudoku(2, 3, 1, 0));
        total.add(new Sudoku(2, 4, 2, 0));
        total.add(new Sudoku(2, 5, 2, 0));
        total.add(new Sudoku(2, 6, 2, 0));
        total.add(new Sudoku(2, 7, 3, 0));
        total.add(new Sudoku(2, 8, 3, 0));
        total.add(new Sudoku(2, 9, 3, 0));
        total.add(new Sudoku(3, 1, 1, 0));
        total.add(new Sudoku(3, 2, 1, 0));
        total.add(new Sudoku(3, 3, 1, 0));
        total.add(new Sudoku(3, 4, 2, 0));
        total.add(new Sudoku(3, 5, 2, 0));
        total.add(new Sudoku(3, 6, 2, 0));
        total.add(new Sudoku(3, 7, 3, 0));
        total.add(new Sudoku(3, 8, 3, 0));
        total.add(new Sudoku(3, 9, 3, 0));
        total.add(new Sudoku(4, 1, 4, 0));
        total.add(new Sudoku(4, 2, 4, 0));
        total.add(new Sudoku(4, 3, 4, 0));
        total.add(new Sudoku(4, 4, 5, 0));
        total.add(new Sudoku(4, 5, 5, 0));
        total.add(new Sudoku(4, 6, 5, 0));
        total.add(new Sudoku(4, 7, 6, 0));
        total.add(new Sudoku(4, 8, 6, 0));
        total.add(new Sudoku(4, 9, 6, 0));
        total.add(new Sudoku(5, 1, 4, 0));
        total.add(new Sudoku(5, 2, 4, 0));
        total.add(new Sudoku(5, 3, 4, 0));
        total.add(new Sudoku(5, 4, 5, 0));
        total.add(new Sudoku(5, 5, 5, 0));
        total.add(new Sudoku(5, 6, 5, 0));
        total.add(new Sudoku(5, 7, 6, 0));
        total.add(new Sudoku(5, 8, 6, 0));
        total.add(new Sudoku(5, 9, 6, 0));
        total.add(new Sudoku(6, 1, 4, 0));
        total.add(new Sudoku(6, 2, 4, 0));
        total.add(new Sudoku(6, 3, 4, 0));
        total.add(new Sudoku(6, 4, 5, 0));
        total.add(new Sudoku(6, 5, 5, 0));
        total.add(new Sudoku(6, 6, 5, 0));
        total.add(new Sudoku(6, 7, 6, 0));
        total.add(new Sudoku(6, 8, 6, 0));
        total.add(new Sudoku(6, 9, 6, 0));
        total.add(new Sudoku(7, 1, 7, 0));
        total.add(new Sudoku(7, 2, 7, 0));
        total.add(new Sudoku(7, 3, 7, 0));
        total.add(new Sudoku(7, 4, 8, 0));
        total.add(new Sudoku(7, 5, 8, 0));
        total.add(new Sudoku(7, 6, 8, 0));
        total.add(new Sudoku(7, 7, 9, 0));
        total.add(new Sudoku(7, 8, 9, 0));
        total.add(new Sudoku(7, 9, 9, 0));
        total.add(new Sudoku(8, 1, 7, 0));
        total.add(new Sudoku(8, 2, 7, 0));
        total.add(new Sudoku(8, 3, 7, 0));
        total.add(new Sudoku(8, 4, 8, 0));
        total.add(new Sudoku(8, 5, 8, 0));
        total.add(new Sudoku(8, 6, 8, 0));
        total.add(new Sudoku(8, 7, 9, 0));
        total.add(new Sudoku(8, 8, 9, 0));
        total.add(new Sudoku(8, 9, 9, 0));
        total.add(new Sudoku(9, 1, 7, 0));
        total.add(new Sudoku(9, 2, 7, 0));
        total.add(new Sudoku(9, 3, 7, 0));
        total.add(new Sudoku(9, 4, 8, 0));
        total.add(new Sudoku(9, 5, 8, 0));
        total.add(new Sudoku(9, 6, 8, 0));
        total.add(new Sudoku(9, 7, 9, 0));
        total.add(new Sudoku(9, 8, 9, 0));
        total.add(new Sudoku(9, 9, 9, 0));
        */

        SudokuCalculator calculator = new SudokuCalculator(total);
        SudokuPrinter printer = new SudokuPrinter();
        printer.printSudoku(total);
        calculator.compute();
    }
}
